

server:
  port: 8099

spring:
  application:
    name: SERVICE-AUTH
  cloud:
    discovery:
      enabled: true




  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: hmayda
    password: hmayda

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
      enabled: true